### ISSUE TITLE
HTML content

### ISSUE THREAD

**Issue by MichelleMcConville** [MichelleMcConville/04-code-quiz#11]

**Comment by cdalangin** [comment]
hi! what html content will you need?

**Comment by MichelleMcConville** [comment]
Hi, Thanks for the offer, but this was for a boot camp coding class and I was trying out the Issues section, not realizing other folks could see this...lol  I understand the HTML part the JavaScript part of the class, well I am trying to understand. :|

**Comment by MichelleMcConville** [comment]
Completed by Mchel
