### ISSUE TITLE
Variables

### ISSUE THREAD

**Issue by MichelleMcConville** [MichelleMcConville/04-code-quiz#16]

**Comment by illegalcall** [comment]
I would like to contribute on as many issues in your project as a part of Hacktoberfest. If you would like that, let me know.

**Comment by MichelleMcConville** [comment]
Hi, Thanks for the offer, but this was for a boot camp coding class and I was trying out the Issues section, not realizing other folks could see this...lol  I think I am done with this assignment!

**Comment by MichelleMcConville** [comment]
Completed by Mchel
